/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import domainModels.HoaDon;
import domainModels.KhachHang;
import domainModels.NhanVien;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import repository.CuaHangRepoSitory;
import repository.HoaDonRepository;
import repository.KhachHangRepository;
import repository.NhanVienRepository;
import service.HoaDonService;
import viewModels.CuaHangViewModel;
import viewModels.HoaDonViewModel;
import viewModels.KhachHangViewModels;

/**
 *
 * @author forre
 */
public class HoaDonView extends javax.swing.JFrame {

    KhachHangRepository khachHang = new KhachHangRepository();
    NhanVienRepository nhanVienRepository = new NhanVienRepository();
    HoaDonRepository hoaDon = new HoaDonRepository();
    HoaDonService hoaDonService = new HoaDonService();

    /**
     * Creates new form HoaDonView
     */
    public HoaDonView() {
        initComponents();
        this.LoadTable();
        this.loadDanhMuc();
        this.loadDanhMuc2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void LoadTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblHoaDon.getModel();
        ArrayList<HoaDonViewModel> hoaDons = hoaDonService.SelectHD();
        dtm.setRowCount(0);
        for (HoaDonViewModel hd : hoaDons) {
            Object row[] = {hd.getId(), hd.getIdKH(),
                hd.getIdNV(), hd.getMa(), hd.getNgayTao(),
                hd.getNgayThanhToan(), hd.getNgayShip(),
                hd.getNgayNhan(), hd.getTinhTrang(),
                hd.getTenNguoiNhan(), hd.getDiaChi(),
                hd.getSoDienThoai()};
            dtm.addRow(row);
        }
    }

    private void loadDanhMuc() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) CbbIdKH.getModel();
        // xoa du lieu cu
        model.removeAllElements();
        model.addElement(null);
        // đỗ dưc liệu mới vào
        ArrayList<KhachHang> khachHangViewModelses = khachHang.SlectKhachHang();
        model.addAll(khachHangViewModelses);

        CbbIdKH.setModel(model);

        // cấu hình chuyên ngành mặc định
        CbbIdKH.setSelectedIndex(0);
    }

    private void loadDanhMuc2() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) CbbIDNV.getModel();
        // xoa du lieu cu
        model.removeAllElements();
        model.addElement(null);
        // đỗ dưc liệu mới vào
        ArrayList<NhanVien> nhanViens = nhanVienRepository.SelectNhanVien();
        model.addAll(nhanViens);

        CbbIDNV.setModel(model);

        // cấu hình chuyên ngành mặc định
        CbbIDNV.setSelectedIndex(0);
    }

    public HoaDon GetFrom() {
        KhachHang idKH = (KhachHang) CbbIdKH.getSelectedItem();
        String idKhachHang = idKH.getId();
        NhanVien idNV = (NhanVien) CbbIDNV.getSelectedItem();
        String idNhanVien = idNV.getId();
        String ma = txtMa.getText();
        String ngayTao = txtNgayTao.getText();
        String ngayThanhToan = txtNgThanhToan.getText();
        String ngaySip = txtNgShip.getText();
        String ngNhan = txtNgNhan.getText();
        String trangThai = txtTinhtrang.getText();
        String tenNgNhan = txtTenNgNhan.getText();
        String diaChi = txtDiaChi.getText();
        String soDt = txtSDT.getText();
        try {
            SimpleDateFormat simple = new SimpleDateFormat("dd-MM-yyyy");
            Date date = simple.parse(ngayTao);
            java.sql.Date sqlDate = new java.sql.Date(date.getTime());
            Date date2 = simple.parse(ngayThanhToan);
            java.sql.Date sqlDate2 = new java.sql.Date(date2.getTime());
            Date date3 = simple.parse(ngaySip);
            java.sql.Date sqlDate3 = new java.sql.Date(date3.getTime());
            Date date4 = simple.parse(ngNhan);
            java.sql.Date sqlDate4 = new java.sql.Date(date4.getTime());
            Integer tt = Integer.valueOf(trangThai);
            HoaDon hoaDon = new HoaDon(idKhachHang, idNhanVien, ma, sqlDate, sqlDate2, sqlDate3, sqlDate4, tt, tenNgNhan, diaChi, soDt);
            return hoaDon;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtMa = new javax.swing.JTextField();
        txtNgayTao = new javax.swing.JTextField();
        txtNgThanhToan = new javax.swing.JTextField();
        txtNgShip = new javax.swing.JTextField();
        txtNgNhan = new javax.swing.JTextField();
        txtTinhtrang = new javax.swing.JTextField();
        txtTenNgNhan = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        CbbIdKH = new javax.swing.JComboBox<>();
        CbbIDNV = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Id");

        jLabel2.setText("IdKhachHang");

        jLabel3.setText("Id NhanVien");

        jLabel4.setText("Mã");

        jLabel5.setText("Ngày Tạo");

        jLabel6.setText("Ngày thanh toán");

        jLabel7.setText("Ngày Ship");

        jLabel8.setText("Ngày Nhận");

        jLabel9.setText("Tình trạng");

        jLabel10.setText("tên người nhận");

        jLabel11.setText("Địa chỉ");

        jLabel12.setText("Số điện thoại");

        txtMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaActionPerformed(evt);
            }
        });

        txtNgThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgThanhToanActionPerformed(evt);
            }
        });

        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "idKH", "idNV", "Ma", "ngayTao", "ngayThanhToan", "ngayShip", "ngayNhan", "tình trạng", "tên ng nhận", "Địa chỉ", "Số Điện thoại"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        btnThem.setText("thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        CbbIdKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CbbIDNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNgThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CbbIDNV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(57, 57, 57)))))
                        .addComponent(btnXoa)
                        .addGap(29, 29, 29)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(CbbIdKH, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(118, 118, 118)
                        .addComponent(txtSDT))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 13, Short.MAX_VALUE))
                            .addComponent(txtNgShip)
                            .addComponent(txtNgNhan)
                            .addComponent(txtTinhtrang)
                            .addComponent(txtTenNgNhan))))
                .addGap(73, 73, 73))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgShip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(txtNgNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbbIdKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTinhtrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTenNgNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CbbIDNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnSua)
                            .addComponent(btnXoa))
                        .addGap(114, 114, 114)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNgThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgThanhToanActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void txtMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        HoaDon p = GetFrom();
        hoaDon.InsertHoaDon(p);
        this.LoadTable();
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        int row = tblHoaDon.getSelectedRow();
        if (row == -1) {
            return;
        }
        String id = tblHoaDon.getValueAt(row, 0).toString();
        String ma = tblHoaDon.getValueAt(row, 3).toString();
        String ngaytao = tblHoaDon.getValueAt(row, 4).toString();
        String ngThanhToan = tblHoaDon.getValueAt(row, 5).toString();
        String ngShip = tblHoaDon.getValueAt(row, 6).toString();
        String ngNhan = tblHoaDon.getValueAt(row, 7).toString();
        String tinhTrang = tblHoaDon.getValueAt(row, 8).toString();
        String tenNgNhan = tblHoaDon.getValueAt(row, 9).toString();
        String DiaChi = tblHoaDon.getValueAt(row, 10).toString();
        String Std = tblHoaDon.getValueAt(row, 11).toString();

        this.txtID.setText(id);
        this.txtMa.setText(ma);

        this.txtNgayTao.setText(ngaytao);
        this.txtNgThanhToan.setText(ngThanhToan);
        this.txtNgShip.setText(ngShip);
        this.txtNgNhan.setText(ngNhan);
        this.txtTinhtrang.setText(tinhTrang);
        this.txtTenNgNhan.setText(tenNgNhan);
        this.txtDiaChi.setText(DiaChi);
        this.txtSDT.setText(Std);
        Object idCHObj = tblHoaDon.getValueAt(row, 1);
        Object idNvObj = tblHoaDon.getValueAt(row, 2);

// Kiểm tra và chuyển đổi thành chuỗi
        String idKH = (idCHObj != null) ? idCHObj.toString() : "";
        String idNV = (idNvObj != null) ? idNvObj.toString() : "";

// Đặt mô hình cho combobox CbbIdCh
        DefaultComboBoxModel<String> idKHModel = new DefaultComboBoxModel<>();
        idKHModel.addElement(idKH);
        CbbIdKH.setModel(idKHModel);

// Đặt mô hình cho combobox CbbIdCV
        DefaultComboBoxModel<String> idNVModel = new DefaultComboBoxModel<>();
        idNVModel.addElement(idNV);
        CbbIDNV.setModel(idNVModel);


    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        String id = txtID.getText();
        hoaDonService.deleteHD(id);
        this.LoadTable();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
       String ma = txtMa.getText();
        String ngayTao = txtNgayTao.getText();
        String ngayThanhToan = txtNgThanhToan.getText();
        String ngaySip = txtNgShip.getText();
        String ngNhan = txtNgNhan.getText();
        String trangThai = txtTinhtrang.getText();
        String tenNgNhan = txtTenNgNhan.getText();
        String diaChi = txtDiaChi.getText();
        String soDt = txtSDT.getText();
        String id = txtID.getText();
        try {
            SimpleDateFormat simple = new SimpleDateFormat("dd-MM-yyyy");
            Date date = simple.parse(ngayTao);
            java.sql.Date sqlDate = new java.sql.Date(date.getTime());
            Date date2 = simple.parse(ngayThanhToan);
            java.sql.Date sqlDate2 = new java.sql.Date(date2.getTime());
            Date date3 = simple.parse(ngaySip);
            java.sql.Date sqlDate3 = new java.sql.Date(date3.getTime());
            Date date4 = simple.parse(ngNhan);
            java.sql.Date sqlDate4 = new java.sql.Date(date4.getTime());
            Integer tt = Integer.valueOf(trangThai);
            hoaDonService.UpdateHD(ma, sqlDate, sqlDate2, sqlDate3, sqlDate4, tt, tenNgNhan, diaChi, soDt, id);
           this.LoadTable();
          
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDonView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbbIDNV;
    private javax.swing.JComboBox<String> CbbIdKH;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtNgNhan;
    private javax.swing.JTextField txtNgShip;
    private javax.swing.JTextField txtNgThanhToan;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNgNhan;
    private javax.swing.JTextField txtTinhtrang;
    // End of variables declaration//GEN-END:variables
}
