/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import domainModels.NhanVien;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import service.ChucVuService;
import service.CuaHangService;
import service.NhanVienService;

import viewModels.ChucVuViewModels;
import viewModels.CuaHangViewModel;
import viewModels.NhanVienViewModels;

/**
 *
 * @author forre
 */
public class NhanVienView extends javax.swing.JFrame {

    /**
     * Creates new form NhanVienView
     */
    public NhanVienView() {
        initComponents();
        this.LoadTable();
        this.loadDanhMuc();
        this.loadDanhMuc2();
        this.loadDanhMuc3();
    }
    NhanVienService nv = new NhanVienService();
    CuaHangService ch = new CuaHangService();
    ChucVuService cv = new ChucVuService();

    public void LoadTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblNv.getModel();
        ArrayList<NhanVienViewModels> nhanviens = nv.SelectNV();
        dtm.setRowCount(0);
        for (NhanVienViewModels nv2 : nhanviens) {
            Object row[] = {nv2.getId(), nv2.getMa(), nv2.getTen(), nv2.getTenDem(), nv2.getHo(),
                nv2.getGioiTinh(), nv2.getNgaySinh(), nv2.getDiaChi(), nv2.getSoDienThoai(),
                nv2.getMatKhau(), nv2.getIdCuaHang(), nv2.getIdChucVu(), nv2.getIdGuiBaoCao(),
                nv2.getTrangThai()};
            dtm.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CbbIdCh = new javax.swing.JComboBox<>();
        CbbIdCV = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtMa = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        TxtTenDem = new javax.swing.JTextField();
        TxtSDT = new javax.swing.JTextField();
        txtHo = new javax.swing.JTextField();
        txtGioiTinh = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtDiaCHi = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        txtTrangThai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNv = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        BtnThem = new javax.swing.JButton();
        CbbIdBCao = new javax.swing.JComboBox<>();
        BtnXoa = new javax.swing.JButton();
        BtnSua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("id");

        jLabel2.setText("mã");

        jLabel3.setText("Tên");

        jLabel4.setText("Tên Đệm");

        jLabel5.setText("Họ");

        jLabel6.setText("Giới Tính");

        jLabel8.setText("Ngày Sinh");

        jLabel9.setText("Địa Chỉ");

        jLabel10.setText("Số Điện Thoại");

        jLabel11.setText("Mật Khẩu");

        CbbIdCh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "null", " " }));
        CbbIdCh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbbIdChActionPerformed(evt);
            }
        });

        CbbIdCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbbIdCVActionPerformed(evt);
            }
        });

        jLabel12.setText("ID Gửi Báo Cáo");

        jLabel13.setText("Trạng thái");

        txtMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauActionPerformed(evt);
            }
        });

        txtTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrangThaiActionPerformed(evt);
            }
        });

        tblNv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "mã", "Tên ", "tên Đệm", "Họ", "Giới tính", "Ngày Sinh", "Địa Chỉ", "Số Điện thoại", "mật khẩu", "Id Cưa hàng", "id Chức Vụ", "id Gửi báo Cao", "Trạng Thái"
            }
        ));
        tblNv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNv);

        jLabel14.setText("id Cửa Hàng");

        jLabel15.setText("id Chức Vụ");

        BtnThem.setText("Thêm");
        BtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemActionPerformed(evt);
            }
        });

        CbbIdBCao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "null", " " }));

        BtnXoa.setText("Xóa");
        BtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnXoaActionPerformed(evt);
            }
        });

        BtnSua.setText("Sửa");
        BtnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel12))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtMa, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTen, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtTenDem, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtSDT, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CbbIdBCao, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CbbIdCh, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(33, 33, 33)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel5)
                                                            .addComponent(jLabel6)))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))))
                                                .addGap(27, 27, 27))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel15))
                                                .addGap(18, 18, 18)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtHo, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                            .addComponent(txtGioiTinh)
                                            .addComponent(txtNgaySinh)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BtnSua)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(txtDiaCHi)
                                            .addComponent(txtMatKhau)
                                            .addComponent(txtTrangThai)
                                            .addComponent(CbbIdCV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(BtnThem)
                                .addGap(174, 174, 174)
                                .addComponent(BtnXoa)))
                        .addGap(376, 376, 376)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel7)
                        .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(TxtTenDem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaCHi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbbIdCh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbbIdCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbbIdBCao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnThem)
                    .addComponent(BtnXoa)
                    .addComponent(BtnSua))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CbbIdChActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbbIdChActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbbIdChActionPerformed

    private void txtTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrangThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrangThaiActionPerformed

    private void CbbIdCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbbIdCVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbbIdCVActionPerformed

    private void txtMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatKhauActionPerformed
    public NhanVien GetFrom() {
        String ma = txtMa.getText();
        String ten = txtTen.getText();
        String dem = TxtTenDem.getText();
        String ho = txtHo.getText();
        String gioiTinh = txtGioiTinh.getText();
        String ngaySinh = txtNgaySinh.getText();
        String diaC = txtDiaCHi.getText();
        String sdt = TxtSDT.getText();
        String matKhau = txtMatKhau.getText();
        NhanVienViewModels idbaocao = (NhanVienViewModels) CbbIdBCao.getSelectedItem();
        String idbc = null;
        if (idbaocao != null) {
            idbc = idbaocao.getId();
        }

        CuaHangViewModel idCh = (CuaHangViewModel) this.CbbIdCh.getSelectedItem();
        String idCuahang = null;
        if (idCh != null) {
            idCuahang = idCh.getId();
        }

        ChucVuViewModels idCV = (ChucVuViewModels) CbbIdCV.getSelectedItem();
        String idchucvu = null;
        if (idCV != null) {
            idchucvu = idCV.getId();
        }
        String trangThai = txtTrangThai.getText();
        Integer tt = Integer.valueOf(trangThai);

        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("dd-MM-yyyy");
        try {
            Date date = simpleDateFormat.parse(ngaySinh);
            java.sql.Date sqldate = new java.sql.Date(date.getTime());
            NhanVien nhanVien = new NhanVien(ma, ten, dem, ho, gioiTinh, sqldate, diaC, sdt, matKhau, idCuahang, idchucvu, idbc, tt);
            return nhanVien;
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        return null;
    }
    private void BtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemActionPerformed
        NhanVien p = GetFrom();
        nv.InsertNhanVien(p);
        this.LoadTable();

    }//GEN-LAST:event_BtnThemActionPerformed

    private void tblNvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNvMouseClicked
        int row = tblNv.getSelectedRow();
        if (row == -1) {
            return;
        }
        String id = tblNv.getValueAt(row, 0).toString();
        String ma = tblNv.getValueAt(row, 1).toString();
        String ten = tblNv.getValueAt(row, 2).toString();
        String dem = tblNv.getValueAt(row, 3).toString();
        String ho = tblNv.getValueAt(row, 4).toString();
        String gioiTinh = tblNv.getValueAt(row, 5).toString();
        String ngaySinh = tblNv.getValueAt(row, 6).toString();
        String diaC = tblNv.getValueAt(row, 7).toString();
        String sdt = tblNv.getValueAt(row, 8).toString();
        String matKhau = tblNv.getValueAt(row, 9).toString();

        String trangThai = tblNv.getValueAt(row, 13).toString();

        this.txtID.setText(id);
        this.txtMa.setText(ma);
        this.txtTen.setText(ten);
        this.TxtTenDem.setText(dem);
        this.txtHo.setText(ho);
        this.txtGioiTinh.setText(gioiTinh);
        this.txtNgaySinh.setText(ngaySinh);
        this.txtDiaCHi.setText(diaC);
        this.TxtSDT.setText(sdt);
        this.txtMatKhau.setText(matKhau);
        Object idCHObj = tblNv.getValueAt(row, 10);
        Object idCVObj = tblNv.getValueAt(row, 11);
        Object idBCObj = tblNv.getValueAt(row, 12);

// Kiểm tra và chuyển đổi thành chuỗi
        String idCH = (idCHObj != null) ? idCHObj.toString() : "";
        String idCV = (idCVObj != null) ? idCVObj.toString() : "";
        String idBC = (idBCObj != null) ? idBCObj.toString() : "";

// Đặt mô hình cho combobox CbbIdCh
        DefaultComboBoxModel<String> idChModel = new DefaultComboBoxModel<>();
        idChModel.addElement(idCH);
        CbbIdCh.setModel(idChModel);

// Đặt mô hình cho combobox CbbIdCV
        DefaultComboBoxModel<String> idCvModel = new DefaultComboBoxModel<>();
        idCvModel.addElement(idCV);
        CbbIdCV.setModel(idCvModel);

// Đặt mô hình cho combobox CbbIdBCao
        DefaultComboBoxModel<String> idBcModel = new DefaultComboBoxModel<>();
        idBcModel.addElement(idBC);
        CbbIdBCao.setModel(idBcModel);
        this.txtTrangThai.setText(trangThai);


    }//GEN-LAST:event_tblNvMouseClicked

    private void BtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnXoaActionPerformed
        String id = txtID.getText();
        nv.DeleteNV(id);
        this.LoadTable();
    }//GEN-LAST:event_BtnXoaActionPerformed

    private void BtnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSuaActionPerformed
        String ma = txtMa.getText();
        String ten = txtTen.getText();
        String dem = TxtTenDem.getText();
        String ho = txtHo.getText();
        String gioiTinh = txtGioiTinh.getText();
        String ngaySinh = txtNgaySinh.getText();
        String diaC = txtDiaCHi.getText();
        String sdt = TxtSDT.getText();
        String matKhau = txtMatKhau.getText();

        // Lấy giá trị từ combobox
        String idCh =  (String) this.CbbIdCh.getSelectedItem();
        String idCV =  (String) CbbIdCV.getSelectedItem();
        
        String idBC = null;
        if((String) CbbIdBCao.getSelectedItem()!=null){
            idBC = (String) CbbIdBCao.getSelectedItem();
        }

        String trangThai = txtTrangThai.getText();
        Integer tt = Integer.valueOf(trangThai);
        String id = txtID.getText();

        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("dd-MM-yyyy");
        try {
            Date date = simpleDateFormat.parse(ngaySinh);
            java.sql.Date sqlDate = new java.sql.Date(date.getTime());

          
            nv.UpdateNV(ma, ten, dem, ho, gioiTinh, sqlDate, diaC, sdt, matKhau, idCh, idCV,idBC, tt, id);

            this.LoadTable();
        } catch (ParseException ex) {
            ex.printStackTrace();
        }


    }//GEN-LAST:event_BtnSuaActionPerformed
    private void loadDanhMuc() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) CbbIdCh.getModel();
        // xoa du lieu cu
        model.removeAllElements();
        model.addElement(null);
        // đỗ dưc liệu mới vào
        ArrayList<CuaHangViewModel> cuaHangs = ch.SelectCH();
        model.addAll(cuaHangs);

        CbbIdCh.setModel(model);

        // cấu hình chuyên ngành mặc định
        CbbIdCh.setSelectedIndex(0);
    }

    private void loadDanhMuc3() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) CbbIdBCao.getModel();
        // xoa du lieu cu
        model.removeAllElements();
        model.addElement(null);
        // đỗ dưc liệu mới vào
        ArrayList<NhanVienViewModels> cuaHangs = nv.SelectNV();
        model.addAll(cuaHangs);

        CbbIdBCao.setModel(model);

        // cấu hình chuyên ngành mặc định
        CbbIdBCao.setSelectedIndex(0);
    }

    private void loadDanhMuc2() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) CbbIdCV.getModel();
        // xoa du lieu cu
        model.removeAllElements();
        model.addElement(null);
        // đỗ dưc liệu mới vào
        ArrayList<ChucVuViewModels> cuaHangs = cv.SelectCV();
        model.addAll(cuaHangs);

        CbbIdCV.setModel(model);

        // cấu hình chuyên ngành mặc định
        CbbIdCV.setSelectedIndex(0);
    }

    /**
     * /
     *
     **
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVienView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSua;
    private javax.swing.JButton BtnThem;
    private javax.swing.JButton BtnXoa;
    private javax.swing.JComboBox<String> CbbIdBCao;
    private javax.swing.JComboBox<String> CbbIdCV;
    private javax.swing.JComboBox<String> CbbIdCh;
    private javax.swing.JTextField TxtSDT;
    private javax.swing.JTextField TxtTenDem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNv;
    private javax.swing.JTextField txtDiaCHi;
    private javax.swing.JTextField txtGioiTinh;
    private javax.swing.JTextField txtHo;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTrangThai;
    // End of variables declaration//GEN-END:variables
}
